import { Button, Col, Row, Modal, Input, Form, Select } from 'antd';
import Head from 'next/head';
import { useState } from 'react';
import { chainMap } from '../chains';

export default function Home() {
  const [modalState, setModalState] = useState(false);
  const [form] = Form.useForm();
  const handaleCancel = () => {
    setModalState(false);
  };

  const formSubmit = (value: any) => {
    console.log(value);
  };

  const selecteChain = Object.keys(chainMap)
    .map((item) => {
      return item;
    })
    .map((item) => {
      return {
        value: item,
        label: chainMap[item].name,
      };
    });

  return (
    <>
      <Head>
        <title>CHAINE DETAILS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="layout">
        <Row align="middle">
          <Col span={12} offset={6}>
            <Button onClick={() => setModalState(true)}>Add Token</Button>
            <Modal
              title={[<h2 className="text-center uppercase">import token</h2>]}
              centered
              closable
              open={modalState}
              onCancel={handaleCancel}
              footer={[]}
            >
              <Form form={form} name="token-info" onFinish={formSubmit}>
                <Form.Item name="networkId" rules={[{ required: true }]}>
                  <Select
                    showSearch
                    placeholder="Select a person"
                    optionFilterProp="children"
                    filterOption={(input, option) =>
                      (option?.label ?? '')
                        .toLowerCase()
                        .includes(input.toLowerCase())
                    }
                    options={selecteChain}
                  />
                </Form.Item>
                <Form.Item name="tokenAddress" rules={[{ required: true }]}>
                  <Input placeholder="Token Address" />
                </Form.Item>
                <Form.Item>
                  <Button type="primary" htmlType="submit">
                    Submit
                  </Button>
                </Form.Item>
              </Form>
            </Modal>
            
          </Col>
        </Row>
      </div>
    </>
  );
}
